### ISSUE TITLE
youtube无法使用

### ISSUE THREAD

**Issue by shenmu33** [youshandefeiyang/IPTV#19]
除了示例的直播地址，自己试了好多直播地址没有一个能用

**Comment by shenmu33** [comment]
比如这个中天新闻的直播 _QbRXRnHMVY
用我自己的youtube代理是可以返回地址的，用网页也能播放

**Comment by shenmu33** [comment]
是不是这个新闻台限制台湾节点，所以你无法解析出来？

**Comment by shenmu33** [comment]
刚刚又发现一个问题
就算能解析的，用本地局域网ip是可以，但是替换成域名就不行，但是bilibili等其他平台用域名也是可以解析的

**Comment by shenmu33** [comment]
> 比如这个中天新闻的直播 _QbRXRnHMVY 用我自己的youtube代理是可以返回地址的，用网页也能播放

这个也无法解析pykpO5kQJ98

**Comment by youshandefeiyang** [comment]
你不应该质疑我群里大神的实力，有问题可以在群里反馈，有时候是自己操作不当或者其他原因，肥羊影音数码管理员没有一个是半吊子

**Comment by youshandefeiyang** [comment]
有问题来群里，这是Popeye的PR作品

**Comment by popeyelau** [comment]
@youshandefeiyang @shenmu33  已修

**Comment by shenmu33** [comment]
> 你不应该质疑我群里大神的实力，有问题可以在群里反馈，有时候是自己操作不当或者其他原因，肥羊影音数码管理员没有一个是半吊子

我并没有加什么群，只是google到这里
没有质疑能力，我也做过程序员，程序有bug在正常不过了
如果说话有得罪请海涵，我的初衷纯粹是为了反馈问题
希望你们越做越好：）

**Comment by youshandefeiyang** [comment]
好的，已解决
