### ISSUE TITLE
windows系统下软件无法打开部署的php

### ISSUE THREAD

**Issue by chyaww** [youshandefeiyang/IPTV#33]
按照教程，用群晖的docker部署了php-env容器，下载了ghyx.php文件并拷贝到了容器内，用vlc、PotPlayer都无法打开，用浏览器打开对应文件出现“Cannot retrieve contributors at this time”提示，docker容器内日志提示各客户端都访问了ghyx.php文件，群里咨询了未果，这里留言看看大佬用空看下啥问题？其他php文件也试了，一样的问题
![2023-04-14_213323](https://user-images.githubusercontent.com/24596610/232067508-5ad0e7c2-18da-4cd1-bae1-53fa6cfbe4fc.jpg)
![2023-04-14_220809](https://user-images.githubusercontent.com/24596610/232067871-80752489-f180-4e87-a34e-f995d70da209.jpg)

**Comment by youshandefeiyang** [comment]
自己的问题，去群里问问大家

**Comment by chyaww** [comment]
没有解决，放弃了，群里问了一圈也说不上所以然，群https://youshandefeiyang.github.io/
