### ISSUE TITLE
想问下肥羊大大，有无可能增加国外一些地区的iptv 播放源文件？？

### ISSUE THREAD

**Issue by P3R5T7U9** [youshandefeiyang/IPTV#34]
如主题所示，之前通过身边一好友的推荐，因为过来翻阅此项目库，尝试了几个播放源文件，加载十分流畅不卡，以前找的其他一些开发者做的国内iptv 播放源文件仓库，基本都需经过“IPTV Checker”检测播放源文件的有效性，剔除失效的源文件后，才能导入到相关播放工具再食用，而肥羊大大目前维护的此项目库，都不用着先用检测工具剔除失效源文件，直接导入食用即可，先感谢肥羊大大一直维护此项目库，辛苦。

最近一直在找霓虹(即日本)五大电视台及一些地方电视台的iptv 播放源文件，急需霓虹国的电视台iptv 播放源，我在此项目库中托管的各个源文件打开都翻阅几遍，妹有一些国外电视台的iptv 播放源文件，不知肥羊大大不收集整理国外电视台的iptv 播放源文件，是因为其一直不在维护计划中？？还是之前由于什么原因(如用户需要挂代理才能播放，维护起来比较麻烦)，导致在创建这个项目库的起始阶段，就放弃收集并维护国外电视台的iptv播放源文件？？😭
(小声：我在创建此issue前，翻阅了之前关闭的那些issue，感觉肥羊大大对每条issue中提问的回复内容很简短，而且不等用户进行楼中楼回复，就将issue关闭了，所以弱弱想麻烦肥羊大大，先仔细看完我开的此issue提问的意思，回复内容稍微长点，方便我这个新手理解，等我二轮回复后，如有进一步的问题，不要先急着关闭issue，让我都搞明白后，由我来关闭issue，你看可以么？？肥羊大大😖)

**Comment by youshandefeiyang** [comment]
只考虑国内的，国外的维护不方便
