### ISSUE TITLE
用docker安装的可以选台吗？

### ISSUE THREAD

**Issue by gxnas** [youshandefeiyang/IPTV#8]
请问一下，在docker安装可以选别的台吗？http://IP:9527/zb.php?id=douyin 这个只能看第一个直播源。

**Comment by HQH3396** [comment]
这个我不太清楚，我也是刚接触这个

**Comment by HQH3396** [comment]
> 请问一下，在docker安装可以选别的台吗？http://IP:9527/zb.php?id=douyin 这个只能看第一个直播源。

这个我也不太清楚，我也是头一次接触这个

**Comment by youshandefeiyang** [comment]
不能选台
